  GNU nano 2.9.3                       DVWA.yml

---
- name: DVWA installer
  hosts: webservers
  become: true
  tasks:

  - name: Install Docker APT
    apt:
      force_apt_get: yes
      name: docker.io
      state: present

  - name: Install Python3-PIP APT
    apt:
      name: python3-pip
      state: present

  - name: Install Docker PIP
    pip:
       name: docker

  - name: Install  DVWA Container
    docker_container:
       name: dvwa
       image: cyberxsecurity/dvwa
       state: started
       published_ports: 80:80

  - name: Enable Docker service
    systemd:
       name: docker
       enabled: yes



